import { Header } from '@/components/header'
import ContextProvider from './context'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${montserrat.className} bg-[#1C1D3B] min-h-screen`}>
        <div className='flex w-full justify-center'>
          <Header />
        </div>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  )
}
